[package]
name = "chess3d"
version = "0.1.0"
authors = ["Nolan K <perpetualcolor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }